from bible_mcp.ingest.importer import BOOK_ORDER


KOREAN_BOOK_ALIASES = {
    "창세기": "Genesis",
    "창": "Genesis",
    "출애굽기": "Exodus",
    "출": "Exodus",
    "레위기": "Leviticus",
    "레": "Leviticus",
    "민수기": "Numbers",
    "민": "Numbers",
    "신명기": "Deuteronomy",
    "신": "Deuteronomy",
    "여호수아": "Joshua",
    "수": "Joshua",
    "사사기": "Judges",
    "삿": "Judges",
    "룻기": "Ruth",
    "룻": "Ruth",
    "사무엘상": "1 Samuel",
    "삼상": "1 Samuel",
    "사무엘하": "2 Samuel",
    "삼하": "2 Samuel",
    "열왕기상": "1 Kings",
    "왕상": "1 Kings",
    "열왕기하": "2 Kings",
    "왕하": "2 Kings",
    "역대상": "1 Chronicles",
    "대상": "1 Chronicles",
    "역대하": "2 Chronicles",
    "대하": "2 Chronicles",
    "에스라": "Ezra",
    "스": "Ezra",
    "느헤미야": "Nehemiah",
    "느": "Nehemiah",
    "에스더": "Esther",
    "에": "Esther",
    "욥기": "Job",
    "욥": "Job",
    "시편": "Psalms",
    "시": "Psalms",
    "잠언": "Proverbs",
    "잠": "Proverbs",
    "전도서": "Ecclesiastes",
    "전": "Ecclesiastes",
    "아가": "Song of Solomon",
    "아": "Song of Solomon",
    "이사야": "Isaiah",
    "사": "Isaiah",
    "예레미야": "Jeremiah",
    "렘": "Jeremiah",
    "예레미야애가": "Lamentations",
    "애가": "Lamentations",
    "애": "Lamentations",
    "에스겔": "Ezekiel",
    "겔": "Ezekiel",
    "다니엘": "Daniel",
    "단": "Daniel",
    "호세아": "Hosea",
    "호": "Hosea",
    "요엘": "Joel",
    "욜": "Joel",
    "아모스": "Amos",
    "암": "Amos",
    "오바댜": "Obadiah",
    "옵": "Obadiah",
    "요나": "Jonah",
    "욘": "Jonah",
    "미가": "Micah",
    "미": "Micah",
    "나훔": "Nahum",
    "나": "Nahum",
    "하박국": "Habakkuk",
    "합": "Habakkuk",
    "스바냐": "Zephaniah",
    "습": "Zephaniah",
    "학개": "Haggai",
    "학": "Haggai",
    "스가랴": "Zechariah",
    "슥": "Zechariah",
    "말라기": "Malachi",
    "말": "Malachi",
    "마태복음": "Matthew",
    "마태": "Matthew",
    "마": "Matthew",
    "마가복음": "Mark",
    "마가": "Mark",
    "막": "Mark",
    "누가복음": "Luke",
    "누가": "Luke",
    "눅": "Luke",
    "요한복음": "John",
    "요한": "John",
    "요": "John",
    "사도행전": "Acts",
    "행": "Acts",
    "로마서": "Romans",
    "롬": "Romans",
    "고린도전서": "1 Corinthians",
    "고전": "1 Corinthians",
    "고린도후서": "2 Corinthians",
    "고후": "2 Corinthians",
    "갈라디아서": "Galatians",
    "갈": "Galatians",
    "에베소서": "Ephesians",
    "엡": "Ephesians",
    "빌립보서": "Philippians",
    "빌": "Philippians",
    "골로새서": "Colossians",
    "골": "Colossians",
    "데살로니가전서": "1 Thessalonians",
    "살전": "1 Thessalonians",
    "데살로니가후서": "2 Thessalonians",
    "살후": "2 Thessalonians",
    "디모데전서": "1 Timothy",
    "딤전": "1 Timothy",
    "디모데후서": "2 Timothy",
    "딤후": "2 Timothy",
    "디도서": "Titus",
    "딛": "Titus",
    "빌레몬서": "Philemon",
    "몬": "Philemon",
    "히브리서": "Hebrews",
    "히": "Hebrews",
    "야고보서": "James",
    "약": "James",
    "베드로전서": "1 Peter",
    "벧전": "1 Peter",
    "베드로후서": "2 Peter",
    "벧후": "2 Peter",
    "요한일서": "1 John",
    "요일": "1 John",
    "요한이서": "2 John",
    "요이": "2 John",
    "요한삼서": "3 John",
    "요삼": "3 John",
    "유다서": "Jude",
    "유": "Jude",
    "요한계시록": "Revelation",
    "계시록": "Revelation",
    "계": "Revelation",
}


BOOK_ALIASES = {book.lower(): book for book in BOOK_ORDER}
BOOK_ALIASES.update({alias.lower(): book for alias, book in KOREAN_BOOK_ALIASES.items()})
